### ISSUE TITLE
OpCodeAdd() issue

### ISSUE THREAD

**Issue by zmm3** [zmm3/ECE-5367-Un-Pipeline#14]
@mttndrsn, the code creates an "error: invalid conversion from 'int*' to 'int' " when trying to pass the parameter in the subroutine.

need to integrate the OpCodeAdd() to return the string that would be output to the output file.

NOTE: the function is commented to be tested for the changes.

**Comment by mttndrsn** [comment]
Hi! Yes, so this is something in C++ that we didn't learn about in Programming in C. I'm sending the variables into the function "by reference" using something like int& PCaddr. This is different from C where you had to send a pointer - you just send the variable but rather than making a copy for the function, it retains its original address and value. so for my function you would just do 
retStr = OpCodeAdd(tempStr, i,  cycleNum,  instrNum);
instead of
retStr = OpCodeAdd(tempStr,&i, &cycleNum, &instrNum);
which is trying to pass an address when it wants an int.
and when i, cycleNum, or instrNum are changed in the function, they are also changed in the main program.
This is similar to passing a pointer, but easier to deal with instead of de-referencing and all that.

**Comment by mttndrsn** [comment]
@zmm3 see above. Try just passing the int variables rather than their addresses. It's a C++ thing that you can't do in C.
